In [68]:
import pandas as pd
from pandas.plotting import scatter_matrix
import mglearn

In [69]:
dataframe = pd.read_csv("data/train.csv")
dataframe.head()

   id  breath_id   R   C  time_step       u_in  u_out   pressure
0   1          1  20  50   0.000000   0.083334      0   5.837492
1   2          1  20  50   0.033652  18.383041      0   5.907794
2   3          1  20  50   0.067514  22.509278      0   7.876254
3   4          1  20  50   0.101542  22.808822      0  11.742872
4   5          1  20  50   0.135756  25.355850      0  12.234987

In [70]:
parameters = dataframe.columns
df_data = dataframe.drop(columns=['pressure','id'])
df_labels = dataframe.drop(columns=list(parameters)[:len(parameters)-1])
df_data.head(), df_labels.head()

(   breath_id   R   C  time_step       u_in  u_out
 0          1  20  50   0.000000   0.083334      0
 1          1  20  50   0.033652  18.383041      0
 2          1  20  50   0.067514  22.509278      0
 3          1  20  50   0.101542  22.808822      0
 4          1  20  50   0.135756  25.355850      0,
     pressure
 0   5.837492
 1   5.907794
 2   7.876254
 3  11.742872
 4  12.234987)

In [71]:
# grr = scatter_matrix(dataframe[:75],c=dataframe['pressure'][:75], figsize=(20,20), marker='o', hist_kwds={'bins': 20}, s=60, alpha=.8, cmap=mglearn.cm3)

In [72]:
labels = df_labels.to_numpy()
data = df_data.to_numpy()

In [73]:
# scatter_matrix(df_data.drop(columns=['id'])[:100], figsize=(15,15), c=labels[:100])

### Scaling data

In [74]:
import sklearn
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()
scalar.fit(df_data.drop(columns='breath_id'))
data_scaled = scalar.transform(df_data.drop(columns='breath_id'))

In [75]:
print(data_scaled.shape)

(6036000, 5)

### Principle components analysis

In [76]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(data_scaled)

data_pca = pca.transform(data_scaled)
print(data_scaled.shape)
print(data_pca.shape)
print(labels)

(6036000, 5)
(6036000, 2)
[[5.83749171]
 [5.90779385]
 [7.87625392]
 ...
 [3.79872949]
 [4.07993807]
 [3.86903163]]

In [77]:
print(data_pca[:10, 0])
print(labels[:10].squeeze())

[-1.73484917 -2.32077394 -2.43158027 -2.41402105 -2.47162382 -2.50789931
 -2.47588074 -2.43757967 -2.44538091 -2.4328659 ]
[ 5.83749171  5.90779385  7.87625392 11.74287192 12.23498694 12.86770625
 14.69556203 15.8906985  15.53918778 15.75009421]

In [78]:
# import matplotlib.pyplot as plt

# plt.figure(figsize=(10,10))

# mglearn.discrete_scatter(data_pca[:, 0], data_pca[:, 1], labels[:].squeeze())
# plt.gca().set_aspect("equal")

### Splitting data

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
X_train, X_test, y_train, y_test = train_test_split(data_scaled, labels, train_size=0.8, random_state=42)

In [81]:
print(X_train.shape, y_test.shape)

(4828800, 5) (1207200, 1)

In [82]:
y_train, y_test = y_train.squeeze(), y_test.squeeze()

In [83]:
X_train_df = pd.DataFrame(X_train)
X_train_df.head()

          0         1         2         3         4
0  1.171893 -0.354513  0.726135 -0.225737  0.782135
1  1.171893  1.394522  0.506360 -0.302757  0.782135
2  1.171893  1.394522 -0.131811 -0.544978  0.782135
3  1.171893 -0.937525 -0.398159 -0.544978  0.782135
4  1.171893 -0.354513 -1.581420 -0.544978 -1.278552

### Tuning gradient boosting regressor hyperparameters

In [84]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV

param_grid = {
    "max_depth": [0,1,2,3,4,5,6,7,8,9,10],
    "learning_rate": [0, 0.1, 0.001, 0.0001]
}

gbr = GradientBoostingRegressor()
grid_search = GridSearchCV(estimator=gbr, param_grid=param_grid, cv=5, n_jobs=-1)

In [85]:
grid_search.fit(X_train[:1000], y_train[:1000])

c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
20 fits failed out of a total of 220.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of GradientBoostingRegressor must be an int in the range [1, inf) or None. Got 0 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [        nan -0.00433171 -0.00433171 -0.00433171 -0.00433171 -0.00433171
 -0.00433171 -0.00433171 -0.00433171 -0.00433171 -0.00433171         nan
  0.5245233   0.55930745  0.57582362  0.55324619  0.54917396  0.52035282
  0.51808354  0.49527052  0.47379567  0.47856699         nan  0.07210213
  0.08548273  0.0882861   0.0936532   0.1026475   0.10667949  0.10901194
  0.10809792  0.10626362  0.10569881         nan  0.0040148   0.00549003
  0.00580091  0.00635178  0.00735057  0.00779321  0.0078398   0.00793221
  0.00788741  0.00790075]
  warnings.warn(

GridSearchCV(cv=5, estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'learning_rate': [0, 0.1, 0.001, 0.0001],
                         'max_depth': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [86]:
best_model = grid_search.best_estimator_

In [87]:
best_model.score(X_test,y_test)

0.6701362087789637

In [88]:
print(grid_search.best_params_)

{'learning_rate': 0.1, 'max_depth': 3}

In [89]:
params = grid_search.best_estimator_.get_params()
params

{'alpha': 0.9,
 'ccp_alpha': 0.0,
 'criterion': 'deprecated',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'squared_error',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [130]:
model_1 = GradientBoostingRegressor(
    alpha=0.9,
    ccp_alpha=0.0,
    criterion='deprecated',
    init=None,
    learning_rate=0.1,
    loss='squared_error',
    max_depth=3,
    max_features=None,
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    min_samples_leaf=1,
    min_samples_split=2,
    min_weight_fraction_leaf=0.0,
    n_estimators=100,
    n_iter_no_change=None,
    random_state=None,
    subsample=1,
    tol=0.0001,
    validation_fraction=0.1,
    verbose=0,
    warm_start=False
)

In [138]:
model_1.fit(X_train[:500000],y_train[:500000])

GradientBoostingRegressor(subsample=1)

In [92]:
scalar.fit(X_test)
X_test_scaled = scalar.transform(X_test)
model_1.score(X_test,y_test), X_test_scaled.shape

(0.7000583468739008, (1207200, 5))

In [93]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from tqdm.auto import tqdm

In [94]:
def accuracy_fn(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item()
    acc = (correct / len(y_pred)) * 100
    return acc

In [95]:
print(X_test.shape)

(1207200, 5)

In [96]:
class BreathModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Sequential(
            nn.Linear(in_features=5, out_features=10),
            nn.ReLU(),
            nn.Linear(in_features=10, out_features=10),
            nn.ReLU(),
            nn.Linear(in_features=10, out_features=1)
        )
        
    def forward(self, x):
        return self.layer1(x)

In [97]:
model_0 = BreathModel()

In [98]:
loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(params=model_0.parameters(),
                             lr=0.001)

In [99]:
BATCH_SIZE = 32

train_data_dataloader = DataLoader(
    dataset=torch.tensor(X_train).type(torch.float32),
    batch_size=BATCH_SIZE,
    shuffle=False
)
train_labels_dataloader = DataLoader(
    dataset=torch.tensor(y_train).type(torch.float32),
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_data_dataloader = DataLoader(
    dataset=torch.tensor(X_test).type(torch.float32),
    batch_size=BATCH_SIZE,
    shuffle=False
)
test_labels_dataloader = DataLoader(
    dataset=torch.tensor(y_test).type(torch.float32),
    batch_size=BATCH_SIZE,
    shuffle=False
)

In [100]:
print(next(iter(train_data_dataloader)).shape)

torch.Size([32, 5])

In [101]:
# for batches in train_data_dataloader:
#     print(batches.shape)

In [102]:
model_0(next(iter(test_data_dataloader))[:32]).shape

torch.Size([32, 1])

In [103]:
next(iter(train_labels_dataloader))[:32].unsqueeze(dim=1).shape

torch.Size([32, 1])

In [104]:
epochs = 3


for epoch in range(epochs):
    print(f"Epoch: {epoch}")
    train_loss = 0
    
    for batches, (X, y) in enumerate(zip(train_data_dataloader, train_labels_dataloader)):
        model_0.train()
        
        y_pred = model_0(X)
        
        if y_pred.ndim == y.unsqueeze(dim=1).ndim:
            loss = loss_fn(y_pred, y.unsqueeze(dim=1))
        else:
            raise ValueError("UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size. return F.mse_loss(input, target, reduction=self.reduction)")
        train_loss += loss
        
        optimizer.zero_grad()
        
        loss.backward()
        
        optimizer.step()
        
        if batches%32 == 0:
            print(f"looked at: {batches/32} samples/{len(train_data_dataloader)/32} of epoch{epoch}/{epochs}")
        
    train_loss /= len(train_data_dataloader)
    
    test_loss, test_acc = 0, 0
    model_0.eval()
    with torch.inference_mode():
        for X_batch,y_batch in zip(test_data_dataloader, test_labels_dataloader):
            test_pred = model_0(X_batch)

            test_loss += loss_fn(test_pred, y_batch.unsqueeze(dim=1))

            # 3. Calculate accuracy
            test_acc += accuracy_fn(y_true=y_batch, y_pred=test_pred.argmax(dim=1))
        
        # Calculate the test loss average per batch
        test_loss /= len(test_data_dataloader)

        # Calculate the test acc average per batch
        test_acc /= len(test_data_dataloader)
    
    # print out what's happening
    print(f"\nTrain loss: {train_loss:.4f} | Test loss: {test_loss:.4f}, Test acc: {test_acc:.4f}")

Epoch: 0
looked at: 0.0 samples
looked at: 1.0 samples
looked at: 2.0 samples
looked at: 3.0 samples
looked at: 4.0 samples
looked at: 5.0 samples
looked at: 6.0 samples
looked at: 7.0 samples
looked at: 8.0 samples
looked at: 9.0 samples
looked at: 10.0 samples
looked at: 11.0 samples
looked at: 12.0 samples
looked at: 13.0 samples
looked at: 14.0 samples
looked at: 15.0 samples
looked at: 16.0 samples
looked at: 17.0 samples
looked at: 18.0 samples
looked at: 19.0 samples
looked at: 20.0 samples
looked at: 21.0 samples
looked at: 22.0 samples
looked at: 23.0 samples
looked at: 24.0 samples
looked at: 25.0 samples
looked at: 26.0 samples
looked at: 27.0 samples
looked at: 28.0 samples
looked at: 29.0 samples
looked at: 30.0 samples
looked at: 31.0 samples
looked at: 32.0 samples
looked at: 33.0 samples
looked at: 34.0 samples
looked at: 35.0 samples
looked at: 36.0 samples
looked at: 37.0 samples
looked at: 38.0 samples
looked at: 39.0 samples
looked at: 40.0 samples
looked at: 41.0 samples
looked at: 42.0 samples
looked at: 43.0 samples
looked at: 44.0 samples
looked at: 45.0 samples
looked at: 46.0 samples
looked at: 47.0 samples
looked at: 48.0 samples
looked at: 49.0 samples
looked at: 50.0 samples
looked at: 51.0 samples
looked at: 52.0 samples
looked at: 53.0 samples
looked at: 54.0 samples
looked at: 55.0 samples
looked at: 56.0 samples
looked at: 57.0 samples
looked at: 58.0 samples
looked at: 59.0 samples
looked at: 60.0 samples
looked at: 61.0 samples
looked at: 62.0 samples
looked at: 63.0 samples
looked at: 64.0 samples
looked at: 65.0 samples
looked at: 66.0 samples
looked at: 67.0 samples
looked at: 68.0 samples
looked at: 69.0 samples
looked at: 70.0 samples
looked at: 71.0 samples
looked at: 72.0 samples
looked at: 73.0 samples
looked at: 74.0 samples
looked at: 75.0 samples
looked at: 76.0 samples
looked at: 77.0 samples
looked at: 78.0 samples
looked at: 79.0 samples
looked at: 80.0 samples
looked at: 81.0 samples
looked at: 82.0 samples
looked at: 83.0 samples
looked at: 84.0 samples
looked at: 85.0 samples
looked at: 86.0 samples
looked at: 87.0 samples
looked at: 88.0 samples
looked at: 89.0 samples
looked at: 90.0 samples
looked at: 91.0 samples
looked at: 92.0 samples
looked at: 93.0 samples
looked at: 94.0 samples
looked at: 95.0 samples
looked at: 96.0 samples
looked at: 97.0 samples
looked at: 98.0 samples
looked at: 99.0 samples
looked at: 100.0 samples
looked at: 101.0 samples
looked at: 102.0 samples
looked at: 103.0 samples
looked at: 104.0 samples
looked at: 105.0 samples
looked at: 106.0 samples
looked at: 107.0 samples
looked at: 108.0 samples
looked at: 109.0 samples
looked at: 110.0 samples
looked at: 111.0 samples
looked at: 112.0 samples
looked at: 113.0 samples
looked at: 114.0 samples
looked at: 115.0 samples
looked at: 116.0 samples
looked at: 117.0 samples
looked at: 118.0 samples
looked at: 119.0 samples
looked at: 120.0 samples
looked at: 121.0 samples
looked at: 122.0 samples
looked at: 123.0 samples
looked at: 124.0 samples
looked at: 125.0 samples
looked at: 126.0 samples
looked at: 127.0 samples
looked at: 128.0 samples
looked at: 129.0 samples
looked at: 130.0 samples
looked at: 131.0 samples
looked at: 132.0 samples
looked at: 133.0 samples
looked at: 134.0 samples
looked at: 135.0 samples
looked at: 136.0 samples
looked at: 137.0 samples
looked at: 138.0 samples
looked at: 139.0 samples
looked at: 140.0 samples
looked at: 141.0 samples
looked at: 142.0 samples
looked at: 143.0 samples
looked at: 144.0 samples
looked at: 145.0 samples
looked at: 146.0 samples
looked at: 147.0 samples
looked at: 148.0 samples
looked at: 149.0 samples
looked at: 150.0 samples
looked at: 151.0 samples
looked at: 152.0 samples
looked at: 153.0 samples
looked at: 154.0 samples
looked at: 155.0 samples
looked at: 156.0 samples
looked at: 157.0 samples
looked at: 158.0 samples
looked at: 159.0 samples
looked at: 160.0 samples
looked at: 161.0 samples
looked at: 162.0 samples
looked at: 163.0 samples
looked at: 164.0 samples
looked at: 165.0 samples
looked at: 166.0 samples
looked at: 167.0 samples
looked at: 168.0 samples
looked at: 169.0 samples
looked at: 170.0 samples
looked at: 171.0 samples
looked at: 172.0 samples
looked at: 173.0 samples
looked at: 174.0 samples
looked at: 175.0 samples
looked at: 176.0 samples
looked at: 177.0 samples
looked at: 178.0 samples
looked at: 179.0 samples
looked at: 180.0 samples
looked at: 181.0 samples
looked at: 182.0 samples
looked at: 183.0 samples
looked at: 184.0 samples
looked at: 185.0 samples
looked at: 186.0 samples
looked at: 187.0 samples
looked at: 188.0 samples
looked at: 189.0 samples
looked at: 190.0 samples
looked at: 191.0 samples
looked at: 192.0 samples
looked at: 193.0 samples
looked at: 194.0 samples
looked at: 195.0 samples
looked at: 196.0 samples
looked at: 197.0 samples
looked at: 198.0 samples
looked at: 199.0 samples
looked at: 200.0 samples
looked at: 201.0 samples
looked at: 202.0 samples
looked at: 203.0 samples
looked at: 204.0 samples
looked at: 205.0 samples
looked at: 206.0 samples
looked at: 207.0 samples
looked at: 208.0 samples
looked at: 209.0 samples
looked at: 210.0 samples
looked at: 211.0 samples
looked at: 212.0 samples
looked at: 213.0 samples
looked at: 214.0 samples
looked at: 215.0 samples
looked at: 216.0 samples
looked at: 217.0 samples
looked at: 218.0 samples
looked at: 219.0 samples
looked at: 220.0 samples
looked at: 221.0 samples
looked at: 222.0 samples
looked at: 223.0 samples
looked at: 224.0 samples
looked at: 225.0 samples
looked at: 226.0 samples
looked at: 227.0 samples
looked at: 228.0 samples
looked at: 229.0 samples
looked at: 230.0 samples
looked at: 231.0 samples
looked at: 232.0 samples
looked at: 233.0 samples
looked at: 234.0 samples
looked at: 235.0 samples
looked at: 236.0 samples
looked at: 237.0 samples
looked at: 238.0 samples
looked at: 239.0 samples
looked at: 240.0 samples
looked at: 241.0 samples
looked at: 242.0 samples
looked at: 243.0 samples
looked at: 244.0 samples
looked at: 245.0 samples
looked at: 246.0 samples
looked at: 247.0 samples
looked at: 248.0 samples
looked at: 249.0 samples
looked at: 250.0 samples
looked at: 251.0 samples
looked at: 252.0 samples
looked at: 253.0 samples
looked at: 254.0 samples
looked at: 255.0 samples
looked at: 256.0 samples
looked at: 257.0 samples
looked at: 258.0 samples
looked at: 259.0 samples
looked at: 260.0 samples
looked at: 261.0 samples
looked at: 262.0 samples
looked at: 263.0 samples
looked at: 264.0 samples
looked at: 265.0 samples
looked at: 266.0 samples
looked at: 267.0 samples
looked at: 268.0 samples
looked at: 269.0 samples
looked at: 270.0 samples
looked at: 271.0 samples
looked at: 272.0 samples
looked at: 273.0 samples
looked at: 274.0 samples
looked at: 275.0 samples
looked at: 276.0 samples
looked at: 277.0 samples
looked at: 278.0 samples
looked at: 279.0 samples
looked at: 280.0 samples
looked at: 281.0 samples
looked at: 282.0 samples
looked at: 283.0 samples
looked at: 284.0 samples
looked at: 285.0 samples
looked at: 286.0 samples
looked at: 287.0 samples
looked at: 288.0 samples
looked at: 289.0 samples
looked at: 290.0 samples
looked at: 291.0 samples
looked at: 292.0 samples
looked at: 293.0 samples
looked at: 294.0 samples
looked at: 295.0 samples
looked at: 296.0 samples
looked at: 297.0 samples
looked at: 298.0 samples
looked at: 299.0 samples
looked at: 300.0 samples
looked at: 301.0 samples
looked at: 302.0 samples
looked at: 303.0 samples
looked at: 304.0 samples
looked at: 305.0 samples
looked at: 306.0 samples
looked at: 307.0 samples
looked at: 308.0 samples
looked at: 309.0 samples
looked at: 310.0 samples
looked at: 311.0 samples
looked at: 312.0 samples
looked at: 313.0 samples
looked at: 314.0 samples
looked at: 315.0 samples
looked at: 316.0 samples
looked at: 317.0 samples
looked at: 318.0 samples
looked at: 319.0 samples
looked at: 320.0 samples
looked at: 321.0 samples
looked at: 322.0 samples
looked at: 323.0 samples
looked at: 324.0 samples
looked at: 325.0 samples
looked at: 326.0 samples
looked at: 327.0 samples
looked at: 328.0 samples
looked at: 329.0 samples
looked at: 330.0 samples
looked at: 331.0 samples
looked at: 332.0 samples
looked at: 333.0 samples
looked at: 334.0 samples
looked at: 335.0 samples
looked at: 336.0 samples
looked at: 337.0 samples
looked at: 338.0 samples
looked at: 339.0 samples
looked at: 340.0 samples
looked at: 341.0 samples
looked at: 342.0 samples
looked at: 343.0 samples
looked at: 344.0 samples
looked at: 345.0 samples
looked at: 346.0 samples
looked at: 347.0 samples
looked at: 348.0 samples
looked at: 349.0 samples
looked at: 350.0 samples
looked at: 351.0 samples
looked at: 352.0 samples
looked at: 353.0 samples
looked at: 354.0 samples
looked at: 355.0 samples
looked at: 356.0 samples
looked at: 357.0 samples
looked at: 358.0 samples
looked at: 359.0 samples
looked at: 360.0 samples
looked at: 361.0 samples
looked at: 362.0 samples
looked at: 363.0 samples
looked at: 364.0 samples
looked at: 365.0 samples
looked at: 366.0 samples
looked at: 367.0 samples
looked at: 368.0 samples
looked at: 369.0 samples
looked at: 370.0 samples
looked at: 371.0 samples
looked at: 372.0 samples
looked at: 373.0 samples
looked at: 374.0 samples
looked at: 375.0 samples
looked at: 376.0 samples
looked at: 377.0 samples
looked at: 378.0 samples
looked at: 379.0 samples
looked at: 380.0 samples
looked at: 381.0 samples
looked at: 382.0 samples
looked at: 383.0 samples
looked at: 384.0 samples
looked at: 385.0 samples
looked at: 386.0 samples
looked at: 387.0 samples
looked at: 388.0 samples
looked at: 389.0 samples
looked at: 390.0 samples
looked at: 391.0 samples
looked at: 392.0 samples
looked at: 393.0 samples
looked at: 394.0 samples
looked at: 395.0 samples
looked at: 396.0 samples
looked at: 397.0 samples
looked at: 398.0 samples
looked at: 399.0 samples
looked at: 400.0 samples
looked at: 401.0 samples
looked at: 402.0 samples
looked at: 403.0 samples
looked at: 404.0 samples
looked at: 405.0 samples
looked at: 406.0 samples
looked at: 407.0 samples
looked at: 408.0 samples
looked at: 409.0 samples
looked at: 410.0 samples
looked at: 411.0 samples
looked at: 412.0 samples
looked at: 413.0 samples
looked at: 414.0 samples
looked at: 415.0 samples
looked at: 416.0 samples
looked at: 417.0 samples
looked at: 418.0 samples
looked at: 419.0 samples
looked at: 420.0 samples
looked at: 421.0 samples
looked at: 422.0 samples
looked at: 423.0 samples
looked at: 424.0 samples
looked at: 425.0 samples
looked at: 426.0 samples
looked at: 427.0 samples
looked at: 428.0 samples
looked at: 429.0 samples
looked at: 430.0 samples
looked at: 431.0 samples
looked at: 432.0 samples
looked at: 433.0 samples
looked at: 434.0 samples
looked at: 435.0 samples
looked at: 436.0 samples
looked at: 437.0 samples
looked at: 438.0 samples
looked at: 439.0 samples
looked at: 440.0 samples
looked at: 441.0 samples
looked at: 442.0 samples
looked at: 443.0 samples
looked at: 444.0 samples
looked at: 445.0 samples
looked at: 446.0 samples
looked at: 447.0 samples
looked at: 448.0 samples
looked at: 449.0 samples
looked at: 450.0 samples
looked at: 451.0 samples
looked at: 452.0 samples
looked at: 453.0 samples
looked at: 454.0 samples
looked at: 455.0 samples
looked at: 456.0 samples
looked at: 457.0 samples
looked at: 458.0 samples
looked at: 459.0 samples
looked at: 460.0 samples
looked at: 461.0 samples
looked at: 462.0 samples
looked at: 463.0 samples
looked at: 464.0 samples
looked at: 465.0 samples
looked at: 466.0 samples
looked at: 467.0 samples
looked at: 468.0 samples
looked at: 469.0 samples
looked at: 470.0 samples
looked at: 471.0 samples
looked at: 472.0 samples
looked at: 473.0 samples
looked at: 474.0 samples
looked at: 475.0 samples
looked at: 476.0 samples
looked at: 477.0 samples
looked at: 478.0 samples
looked at: 479.0 samples
looked at: 480.0 samples
looked at: 481.0 samples
looked at: 482.0 samples
looked at: 483.0 samples
looked at: 484.0 samples
looked at: 485.0 samples
looked at: 486.0 samples
looked at: 487.0 samples
looked at: 488.0 samples
looked at: 489.0 samples
looked at: 490.0 samples
looked at: 491.0 samples
looked at: 492.0 samples
looked at: 493.0 samples
looked at: 494.0 samples
looked at: 495.0 samples
looked at: 496.0 samples
looked at: 497.0 samples
looked at: 498.0 samples
looked at: 499.0 samples
looked at: 500.0 samples
looked at: 501.0 samples
looked at: 502.0 samples
looked at: 503.0 samples
looked at: 504.0 samples
looked at: 505.0 samples
looked at: 506.0 samples
looked at: 507.0 samples
looked at: 508.0 samples
looked at: 509.0 samples
looked at: 510.0 samples
looked at: 511.0 samples
looked at: 512.0 samples
looked at: 513.0 samples
looked at: 514.0 samples
looked at: 515.0 samples
looked at: 516.0 samples
looked at: 517.0 samples
looked at: 518.0 samples
looked at: 519.0 samples
looked at: 520.0 samples
looked at: 521.0 samples
looked at: 522.0 samples
looked at: 523.0 samples
looked at: 524.0 samples
looked at: 525.0 samples
looked at: 526.0 samples
looked at: 527.0 samples
looked at: 528.0 samples
looked at: 529.0 samples
looked at: 530.0 samples
looked at: 531.0 samples
looked at: 532.0 samples
looked at: 533.0 samples
looked at: 534.0 samples
looked at: 535.0 samples
looked at: 536.0 samples
looked at: 537.0 samples
looked at: 538.0 samples
looked at: 539.0 samples
looked at: 540.0 samples
looked at: 541.0 samples
looked at: 542.0 samples
looked at: 543.0 samples
looked at: 544.0 samples
looked at: 545.0 samples
looked at: 546.0 samples
looked at: 547.0 samples
looked at: 548.0 samples
looked at: 549.0 samples
looked at: 550.0 samples
looked at: 551.0 samples
looked at: 552.0 samples
looked at: 553.0 samples
looked at: 554.0 samples
looked at: 555.0 samples
looked at: 556.0 samples
looked at: 557.0 samples
looked at: 558.0 samples
looked at: 559.0 samples
looked at: 560.0 samples
looked at: 561.0 samples
looked at: 562.0 samples
looked at: 563.0 samples
looked at: 564.0 samples
looked at: 565.0 samples
looked at: 566.0 samples
looked at: 567.0 samples
looked at: 568.0 samples
looked at: 569.0 samples
looked at: 570.0 samples
looked at: 571.0 samples
looked at: 572.0 samples
looked at: 573.0 samples
looked at: 574.0 samples
looked at: 575.0 samples
looked at: 576.0 samples
looked at: 577.0 samples
looked at: 578.0 samples
looked at: 579.0 samples
looked at: 580.0 samples
looked at: 581.0 samples
looked at: 582.0 samples
looked at: 583.0 samples
looked at: 584.0 samples
looked at: 585.0 samples
looked at: 586.0 samples
looked at: 587.0 samples
looked at: 588.0 samples
looked at: 589.0 samples
looked at: 590.0 samples
looked at: 591.0 samples
looked at: 592.0 samples
looked at: 593.0 samples
looked at: 594.0 samples
looked at: 595.0 samples
looked at: 596.0 samples
looked at: 597.0 samples
looked at: 598.0 samples
looked at: 599.0 samples
looked at: 600.0 samples
looked at: 601.0 samples
looked at: 602.0 samples
looked at: 603.0 samples
looked at: 604.0 samples
looked at: 605.0 samples
looked at: 606.0 samples
looked at: 607.0 samples
looked at: 608.0 samples
looked at: 609.0 samples
looked at: 610.0 samples
looked at: 611.0 samples
looked at: 612.0 samples
looked at: 613.0 samples
looked at: 614.0 samples
looked at: 615.0 samples
looked at: 616.0 samples
looked at: 617.0 samples
looked at: 618.0 samples
looked at: 619.0 samples
looked at: 620.0 samples
looked at: 621.0 samples
looked at: 622.0 samples
looked at: 623.0 samples
looked at: 624.0 samples
looked at: 625.0 samples
looked at: 626.0 samples
looked at: 627.0 samples
looked at: 628.0 samples
looked at: 629.0 samples
looked at: 630.0 samples
looked at: 631.0 samples
looked at: 632.0 samples
looked at: 633.0 samples
looked at: 634.0 samples
looked at: 635.0 samples
looked at: 636.0 samples
looked at: 637.0 samples
looked at: 638.0 samples
looked at: 639.0 samples
looked at: 640.0 samples
looked at: 641.0 samples
looked at: 642.0 samples
looked at: 643.0 samples
looked at: 644.0 samples
looked at: 645.0 samples
looked at: 646.0 samples
looked at: 647.0 samples
looked at: 648.0 samples
looked at: 649.0 samples
looked at: 650.0 samples
looked at: 651.0 samples
looked at: 652.0 samples
looked at: 653.0 samples
looked at: 654.0 samples
looked at: 655.0 samples
looked at: 656.0 samples
looked at: 657.0 samples
looked at: 658.0 samples
looked at: 659.0 samples
looked at: 660.0 samples
looked at: 661.0 samples
looked at: 662.0 samples
looked at: 663.0 samples
looked at: 664.0 samples
looked at: 665.0 samples
looked at: 666.0 samples
looked at: 667.0 samples
looked at: 668.0 samples
looked at: 669.0 samples
looked at: 670.0 samples
looked at: 671.0 samples
looked at: 672.0 samples
looked at: 673.0 samples
looked at: 674.0 samples
looked at: 675.0 samples
looked at: 676.0 samples
looked at: 677.0 samples
looked at: 678.0 samples
looked at: 679.0 samples
looked at: 680.0 samples
looked at: 681.0 samples
looked at: 682.0 samples
looked at: 683.0 samples
looked at: 684.0 samples
looked at: 685.0 samples
looked at: 686.0 samples
looked at: 687.0 samples
looked at: 688.0 samples
looked at: 689.0 samples
looked at: 690.0 samples
looked at: 691.0 samples
looked at: 692.0 samples
looked at: 693.0 samples
looked at: 694.0 samples
looked at: 695.0 samples
looked at: 696.0 samples
looked at: 697.0 samples
looked at: 698.0 samples
looked at: 699.0 samples
looked at: 700.0 samples
looked at: 701.0 samples
looked at: 702.0 samples
looked at: 703.0 samples
looked at: 704.0 samples
looked at: 705.0 samples
looked at: 706.0 samples
looked at: 707.0 samples
looked at: 708.0 samples
looked at: 709.0 samples
looked at: 710.0 samples
looked at: 711.0 samples
looked at: 712.0 samples
looked at: 713.0 samples
looked at: 714.0 samples
looked at: 715.0 samples
looked at: 716.0 samples
looked at: 717.0 samples
looked at: 718.0 samples
looked at: 719.0 samples
looked at: 720.0 samples
looked at: 721.0 samples
looked at: 722.0 samples
looked at: 723.0 samples
looked at: 724.0 samples
looked at: 725.0 samples
looked at: 726.0 samples
looked at: 727.0 samples
looked at: 728.0 samples
looked at: 729.0 samples
looked at: 730.0 samples
looked at: 731.0 samples
looked at: 732.0 samples
looked at: 733.0 samples
looked at: 734.0 samples
looked at: 735.0 samples
looked at: 736.0 samples
looked at: 737.0 samples
looked at: 738.0 samples
looked at: 739.0 samples
looked at: 740.0 samples
looked at: 741.0 samples
looked at: 742.0 samples
looked at: 743.0 samples
looked at: 744.0 samples
looked at: 745.0 samples
looked at: 746.0 samples
looked at: 747.0 samples
looked at: 748.0 samples
looked at: 749.0 samples
looked at: 750.0 samples
looked at: 751.0 samples
looked at: 752.0 samples
looked at: 753.0 samples
looked at: 754.0 samples
looked at: 755.0 samples
looked at: 756.0 samples
looked at: 757.0 samples
looked at: 758.0 samples
looked at: 759.0 samples
looked at: 760.0 samples
looked at: 761.0 samples
looked at: 762.0 samples
looked at: 763.0 samples
looked at: 764.0 samples
looked at: 765.0 samples
looked at: 766.0 samples
looked at: 767.0 samples
looked at: 768.0 samples
looked at: 769.0 samples
looked at: 770.0 samples
looked at: 771.0 samples
looked at: 772.0 samples
looked at: 773.0 samples
looked at: 774.0 samples
looked at: 775.0 samples
looked at: 776.0 samples
looked at: 777.0 samples
looked at: 778.0 samples
looked at: 779.0 samples
looked at: 780.0 samples
looked at: 781.0 samples
looked at: 782.0 samples
looked at: 783.0 samples
looked at: 784.0 samples
looked at: 785.0 samples
looked at: 786.0 samples
looked at: 787.0 samples
looked at: 788.0 samples
looked at: 789.0 samples
looked at: 790.0 samples
looked at: 791.0 samples
looked at: 792.0 samples
looked at: 793.0 samples
looked at: 794.0 samples
looked at: 795.0 samples
looked at: 796.0 samples
looked at: 797.0 samples
looked at: 798.0 samples
looked at: 799.0 samples
looked at: 800.0 samples
looked at: 801.0 samples
looked at: 802.0 samples
looked at: 803.0 samples

In [105]:
model_0(next(iter(test_data_dataloader))[:10]), next(iter(test_labels_dataloader))[:10]

(tensor([[ 4.9415],
         [ 8.1006],
         [20.1806],
         [ 6.9369],
         [20.1941],
         [19.3690],
         [12.7379],
         [16.1028],
         [ 6.9224],
         [20.0614]], grad_fn=<AddmmBackward0>),
 tensor([ 4.5018,  8.2278, 14.2737,  6.1187, 18.5622, 17.8592, 10.4774, 14.2034,
          6.8217, 34.8020]))

In [111]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

In [128]:
pred = model_0(next(iter(test_data_dataloader))).squeeze().detach().numpy()
true_test_labels = next(iter(test_labels_dataloader)).detach().numpy()
mse = mean_squared_error(true_test_labels, pred)
mae = mean_absolute_error(true_test_labels, pred)
r2 = r2_score(true_test_labels, pred)
print(f"(MAE): {mae}: An MAE of {mae} indicates that, on average, the model’s predictions deviate from the actual values by approximately {mae} units.")
print(f"(MSE): {mse}: An MSE of {mse} shows that the average of the squared prediction errors is {mse}, meaning the model incurs some large errors that are heavily penalized.")
print(f"(R²): {r2}: An R² value of {r2} indicates that the model explains approximately {r2*100:.2f}% of the variance in the target variable, reflecting moderate predictive capability.")
print(f"(RMSE): : An RMSE of {np.sqrt(mse)} suggests that the model’s predictions typically differ from the actual values by about {np.sqrt(mse)} units, in the same scale as the target variable.")

(MAE): 2.8370800018310547: An MAE of 2.8370800018310547 indicates that, on average, the model’s predictions deviate from the actual values by approximately 2.8370800018310547 units.
(MSE): 25.912456512451172: An MSE of 25.912456512451172 shows that the average of the squared prediction errors is 25.912456512451172, meaning the model incurs some large errors that are heavily penalized.
(R²): 0.6907756924629211: An R² value of 0.6907756924629211 indicates that the model explains approximately 69.08% of the variance in the target variable, reflecting moderate predictive capability.
(RMSE): : An RMSE of 5.090427930189286 suggests that the model’s predictions typically differ from the actual values by about 5.090427930189286 units, in the same scale as the target variable.

#### model_1: tree-based model
#### model_0 : neural network

In [143]:
model_1.predict(X_test_scaled)[:5], y_test[:5]

(array([ 5.63253803,  6.96513598, 22.09172986,  6.213493  , 21.33522729]),
 array([ 4.50175094,  8.22776465, 14.27374916,  6.11870029, 18.56218003]))

In [139]:
tree_based_model_prediction = model_1.predict(X_test_scaled)
tree_mse = mean_squared_error(y_test, tree_based_model_prediction)
tree_mae = mean_absolute_error(y_test, tree_based_model_prediction)
tree_r2 = r2_score(y_test, tree_based_model_prediction)
print(tree_mse, tree_mae, tree_r2)

22.011399985787712 2.468850262450004 0.6653838773395785

In [141]:
tree_performance = [tree_mae, tree_mse, f"{tree_r2*100:.2f}%", np.sqrt(tree_mse)]
nn_performance = [mae, mse, f"{r2*100:.2f}%", np.sqrt(mse)]
scoring_system = ["MAE", "MSE", "R2", "SMSE"]
comparing_data = {
    "Tree-based model": tree_performance,
    "Neural Network": nn_performance
}

comparing_df = pd.DataFrame(comparing_data, index=scoring_system)

comparing_df

     Tree-based model Neural Network
MAE           2.46885        2.83708
MSE           22.0114      25.912457
R2             66.54%         69.08%
SMSE         4.691631       5.090428